"""Generates src/lib/globe.ts: a pixel planet for the world picker.

MAP is an 80x40 wrap-around world texture (scrolled inside the disc so the planet turns),
SHADE is the 40x40 disc: outline, night-side shade and a highlight. Run: python tools/globe_gen.py
"""
import json, math, os, random

W, H, R = 80, 40, 20  # texture width (wraps), height = disc diameter
random.seed(11)

def lattice(cells_x, cells_y):
    return [[random.random() for _ in range(cells_x)] for _ in range(cells_y + 1)]

def noise(grid, cells_x, x, y):
    """Bilinear value noise, periodic in x so the texture wraps seamlessly."""
    gx, gy = x / W * cells_x, y / (H - 1) * (len(grid) - 1)
    x0, y0 = int(gx) % cells_x, min(int(gy), len(grid) - 2)
    fx, fy = gx - int(gx), gy - int(gy)
    fx, fy = fx * fx * (3 - 2 * fx), fy * fy * (3 - 2 * fy)
    x1 = (x0 + 1) % cells_x
    a = grid[y0][x0] * (1 - fx) + grid[y0][x1] * fx
    b = grid[y0 + 1][x0] * (1 - fx) + grid[y0 + 1][x1] * fx
    return a * (1 - fy) + b * fy

octaves = [(lattice(c, c // 2), c, w) for c, w in ((5, 0.6), (10, 0.28), (20, 0.12))]
def height(x, y):
    return sum(noise(g, c, x, y) * w for g, c, w in octaves)

hs = [[height(x, y) for x in range(W)] for y in range(H)]
flat = sorted(v for row in hs for v in row)
sea = flat[int(len(flat) * 0.62)]  # ~38% land, like the reference
rows = []
for y in range(H):
    lat = abs(y - (H - 1) / 2) / ((H - 1) / 2)  # 0 equator .. 1 pole
    row = ''
    for x in range(W):
        h = hs[y][x]
        if lat > 0.9 or (lat > 0.8 and h > sea - 0.03):
            row += 'i' if (x + y) % 5 else 'I'  # ice caps
        elif h < sea:
            d = sea - h
            row += 'L' if d < 0.025 else 'O' if d < 0.09 else 'D'  # shallows -> deep
        else:
            u = h - sea
            arid = 0.25 < lat < 0.55  # desert belts
            row += ('s' if u < 0.02 else 'S' if u > 0.12 else 's') if arid and u < 0.12 or u < 0.012 else 'G' if u > 0.07 else 'g'
    rows.append(row)

shade = []
c = (R - 0.5, R - 0.5)
for y in range(2 * R):
    row = ''
    for x in range(2 * R):
        d = math.hypot(x - c[0], y - c[1])
        if d > R - 0.2:
            row += '.'
        elif d > R - 1.4:
            row += 'k'  # outline
        else:
            # light from the top-left: rim on the far side goes dark, a small hotspot top-left
            lx, ly = (x - c[0]) / R, (y - c[1]) / R
            lit = -(lx * 0.6 + ly * 0.6) + math.sqrt(max(0, 1 - lx * lx - ly * ly)) * 0.5
            row += 'h' if lit > 0.95 else 'x' if lit < -0.35 else 'd' if lit < -0.05 else '-'
    shade.append(row)

out = f'''// Generated by tools/globe_gen.py — edit the generator, not this file.
// Pixel planet for the world picker: MAP wraps horizontally (scrolled so the planet turns), SHADE is the disc.
export const GLOBE_PAL: Record<string, string> = {{
  D: '#1f2f86', O: '#2c48b0', L: '#4a78d6', // ocean deep / mid / shallow
  g: '#6aa83a', G: '#3f7a2a', s: '#d1b04a', S: '#a4822c', // land green / forest / sand / dry hills
  i: '#e4f6f8', I: '#a8d8e0', // ice
}}
export const GLOBE_SHADE_PAL: Record<string, string> = {{ k: '#0a0c24', h: '#ffffff55', d: '#0a0c2455', x: '#0a0c24aa', '-': '#00000000' }}
export const GLOBE_MAP: string[] = {json.dumps(rows, indent=2)}
export const GLOBE_SHADE: string[] = {json.dumps(shade, indent=2)}
'''
path = os.path.join(os.path.dirname(__file__), '..', 'src', 'lib', 'globe.ts')
open(path, 'w', encoding='utf-8').write(out)
print('\n'.join(rows[::2]))
